# doc: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
name: events
run-name: Events

# Adicionando eventos para branches específicas
on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

# Adicionando eventos para todas as branches
# on:
#   - push
#   - pull_request

jobs:
  show-ref-and-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GITHUB_SHA and GITHUB_REF
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF