name: filter-events
run-name: Filter Events

on:
  pull_request:
    branches:
      - "feature/**"
    paths:
      - "**.rb"

jobs:
  show-ref-and-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GITHUB_SHA and GITHUB_REF
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF