name: shell-and-workdirs
run-name: Shells e Diretorios de trabalho

on:
  - push

jobs:
  display-workdir-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display workdir and list files
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE